version: '3.8'

services:
  kapitto_snippet-manager:
    image: eravse/kapitto_snippet_manager:amd-64-latest
    container_name: kapitto_snippet_manager
    ports:
      - "3012:3000"
    restart: always
    volumes:
      - ./prisma/data:/prisma/data
